graph TD
  A([Mulai]) --> B["Input n orde"]
  B --> C["Inisialisasi data x, y, vander = [], x_ = [], iterasi = 0"]
  C --> D["i = 0 to len(x)"]
  D -- No --> E["X = np.array(vander)"]
  D -- Yes --> Z["pangkat = 0"]
  Z --> AA["j = 0 to (n + 1)"]
  AA -- Yes --> AB["hasil = x[i]**pangkat, pangkat += 1, x_.append(hasil)"]
  AA --No --> AC["vander.append(x_), x_ = []"]
  E --> F[" Xt = np.transpose(X)"]
  F --> AAD["M = np.dot(Xt, X)"]
  AAD --> AD["M1 = np.linalg.inv(M)"]
  AD --> AE["np.transpose(y)"]
  AE --> AF["beta = np.dot(np.dot(M1, Xt), Yt)"]
  AF --> AG["x1 = np.arange(min(x),max(x) + 0.1,0.1)"]
  AG --> AH["y1 = []"]
  AH --> AI["hasil = 0"]
  AI ---> AJ["i = 0 to len(x)"]
  AJ -- Yes --> G["pangkat = 0"]
  G --> H["j = 0 to (n + 1)"]
  H -- Yes --> J["hasil += beta[j]*x1[i]**pangkat, pangkat += 1"]
  H -- No --> I["y1.append(hasil), hasil = 0)"]
  AJ -- No --> AK["y2 = [], jumlah = 0"]
  AK --> AL["i = 0 to len(x)"]
  AL -- Yes --> AM["pangkat = 0"]
  AM --> AN["j = 0 to (n + 1)"]
  AN -- Yes --> AO["jumlah += beta[j]*x[i]**pangkat, pangkat +=1"]
  AN -- No --> AP["y2.append(jumlah), jumlah = 0"]
  AL -- No --> AQ["D2 = 0, Dt = 0, y_bar = 0"]
  AQ --> AS["i = 0 to len(y)"]
  AS -- Yes --> AT["y_bar += y[i]"]
  AS -- No --> AU["y_bar = y_bar/len(y)"]
  AU --> AV["i = 0 to len(x)"]
  AV -- Yes --> AW["D2 += (y[i]-y2[i])**2"]
  AW --> AX["Dt += (y[i]-y_bar)**2"]
  AV -- No --> AY["R = ((Dt - D2)/ Dt)**0.5"]
  AY --> AZ["plt.scatter(x, y)"]
  AZ --> AAA["plt.plot(x1, y1, label = 'R:%.4f' %R)"]
  AAA --> AAB["plt.legend()"]
  AAB --> AAC["plt.show()"]


  
  
  AAC --> O([Selesai])
