flowchart TD;
    A[start] --> B["Inisialisasi:f(x), a = nilai batas awal, b = nilai batas akhir,tol = nilai toleransi, maxIter = maksimum iterasi, iter = 0"]
    B --> Z["Def falsePosition"]
    Z --> C{{"f(a)f(b) > 0"}}
    C --> D["PRINT: error, a,b terlalu besar"]
    Z --> G{{"e > 0.0001"}}
    G -->H["c = (f(b)a - f(a)b)/(f(b)-f(a))"]
    H --> I{"|f(c)| < 0"}
    I -->|YES| J["break"]
    I -->|NO| K{"f(a)f(c) < 0"} 
    K --> |YES| L["b = c"]
    K --> |NO| M["a = c"]
    G --> N["iter += 1"]
    Z --> X["return c, iter, e"]
