graph TD
  A([Mulai]) --> B["Input matriks A"]
  B --> C["Inisialisasi x0, e, eigen_lama, iterasi"]
  C --> D["Input toleransi"]
  D -->|det ≠ 0| E["Hitung invers B = inv(A)"]
  D -->|det = 0| Z["Print "Matriks tidak dapat diinverskan""]
  E --> F{"e > toleransi?"}
  F -- Yes --> G["Hitung y = B * x0"]
  G --> H["Hitung eigen_baru = max(y)"]
  H --> I["Hitung x = y / eigen_baru"]
  I --> J["Hitung e = |(eigen_lama - eigen_baru) / eigen_lama|"]
  J --> K["iterasi += 1"]
  K --> L["Update eigen_lama = eigen_baru"]
  L --> G
  G -- No --> P["Hitung nilai_eigen = 1 / eigen_baru"]
  P --> Q["Print Nilai Eigen dan vektor x"]
  Q --> O([Selesai])
