graph TD
  A([Mulai]) --> B["Input matriks A"]
  B --> C["Input vektor awal x0"]
  C --> D["Input toleransi"]
  D -->|det ≠ 0| E["Hitung invers B = inv(A)"]
  D -->|det = 0| Z["Print "Matriks tidak dapat diinverskan""]
  E --> F["Inisialisasi x0, e, eigen_lama, iterasi"]
  F --> G{"e > toleransi?"}
  G -- Yes --> H["Hitung y = B * x0"]
  H --> I["Hitung eigen_baru = max(y)"]
  I --> J["Hitung x = y / eigen_baru"]
  J --> K["Hitung e = |(eigen_lama - eigen_baru) / eigen_lama|"]
  K --> L["iterasi += 1"]
  L --> M["Update eigen_lama = eigen_baru"]
  M --> Q
  G -- No --> P["Hitung nilai_eigen = 1 / eigen_baru"]
  P --> Q["Print Nilai Eigen dan vektor x"]
  Q --> O([Selesai])
